#!/bin/bash

if [ -z "$MY_PINBALL_INSTALL" ]
then
  echo "ERROR: Environment variable MY_PINBALL_INSTALL not defined"
  exit 1
fi

cd $MY_PINBALL_INSTALL/src
g++ `pkg-config --cflags --libs gtk+-2.0` -Wall -DDYNAMIC_TRACE_FILTER -DTF_INTEGRATED_TRACE_LOG -I../include \
myPinball.cc \
Playfield.cc \
Module.cc \
Rules.cc \
Utils.cc \
Timer.cc \
QueueThread.cc \
-lpthread -lpshell-server \
-o ../bin/myPinball `pkg-config --libs gtk+-2.0`
  
